### ISSUE TITLE
Enabling hackvector for Response

### ISSUE THREAD

**Issue by Hipapheralkus** [hackvertor/hackvertor#10]
Perfect and very powerful extension, many thanks:)
I was wondering, if you could add a Hackvector tab into the response as well. A sample usecase:
When I know that the vulnerability exists, but the output is encoded in Base64 inside special tags (<Data></Data> in this example), I would like to write the rule, and then apply it to the response in the Repeater, to very simply observe the behaviour. The rule could be something like
`<@d_base64_0><@regex_replace_0("<(\/?)Data>","")><@find_0("<Data>(.*)</Data>")>........To be applied to the whole response....<@/find_0><@/regex_replace_0><@/d_base64_0>`
which would allow me to parse for <Data> tags, and base64 decode what is inside, for me to easily observe, what is happening:)

**Comment by hackvertor** [comment]
Hi Hipapheralkus, thanks and glad you like the extension. At the moment you can right click on responses and send them to Hackvertor but I can add a Message editor tab on responses that would be quite easy. I'll let you know when it's in.

**Comment by hackvertor** [comment]
Sorry for the delay but I've now pushed this change. You should be able to use Hackvertor in responses now. It will be on the BApp store next week. Cheers.
