### ISSUE TITLE
Basic editing and navigational keys are not working on Windows 10

### ISSUE THREAD

**Issue by dp4099** [hackvertor/hackvertor#100]
Basic editing and navigational keys such as ENTER, Backspace, Delete, right/left arrows keys are not working on Windows 10. They just don't do anything when pressed. The keys were working fine before.

**Environment:**
Windows 10 Pro (version 10.0.19045 Build 19045)
Burp Suite Prof v2023.10.1.1
Latest version of Hackvertor (v1.7.49)
jython-standalone-2.7.2.jar
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

**Comment by hackvertor** [comment]
Ugh I don't know what went wrong here. Maybe it's something to do with RSyntaxTextarea. Is Hackvertor the only extension enabled? I'll investigate to see what's going on.

**Comment by dp4099** [comment]
No, I have other extension loaded.

**Comment by hackvertor** [comment]
Thanks for the info

**Comment by dp4099** [comment]
I think the problem started happening when I re-organized the order of the extensions. Not sure if the order of the extensions is important or not. The Hackvertor extension was placed near the bottom of the list. When I moved this extension to the top, the problem went away! 

I did some testing and found that if I placed the Hackvertor load order after these extensions:
Retire.js, Logger++, and JSON Web Tokens, the problem reappeared.

If I moved Hackvertor load order up one or two times, the problem goes away.

![Hackvertor-load-order-7](https://github.com/hackvertor/hackvertor/assets/10893071/50b29d09-d0d1-461e-9a6c-a1a3ef520da5)

**Comment by hackvertor** [comment]
Interesting did you manage to log any exceptions? So I can see what causes this.

**Comment by dp4099** [comment]
Here is the exception log.
[prgtqqs1khtjv4wsw0q5_llfm_09-10-2023_ExceptionLog.txt](https://github.com/hackvertor/hackvertor/files/12851071/prgtqqs1khtjv4wsw0q5_llfm_09-10-2023_ExceptionLog.txt)

**Comment by dp4099** [comment]
@hackvertor, all the keys work in the Hackvertor tab when I moved this extension to the top of the extension list. However, the Hackvertor tab inside the Repeater still has the same problem. The following keys are not functioning:

Regular keys:  ( [ { } ` / ' "
Special keys:  [Enter], [Backspace], [Home], [End], [Delete], and arrow keys

**Comment by dp4099** [comment]
@hackvertor , I found the problem! The keys worked from the Hackvertor tab inside the Repeater when I unloaded the "JWT Editor" extension (https://github.com/portswigger/jwt-editor).

**Comment by hackvertor** [comment]
Thanks that's really useful

**Comment by hackvertor** [comment]
We've patched the JWT extension to fix this problem. Thanks so much for the report! The information you gave us was really valuable.
