### ISSUE TITLE
UTF-7 encoder

### ISSUE THREAD

**Issue by ngregoire** [hackvertor/hackvertor#11]
Hello,

I noticed that Hackvertor v1.1 (as available from the BAppStore) doesn't include a UTF-7 encoder. As UTF-7 is useful in a few situations (mostly WAF bypasses for XXE), I'd like to have it easily available in Hackvertor.

My current solution is to use raw Python code:

    <@python_17("import base64;output = ''.join('+%s-' % base64.b64encode(chr(0) + c).rstrip('=') for c in input)","c87cd506bfd8c83f74e81ba5909a3211")><xml><XXE/></xml><@/python_17>

Output:

    ADw-+AHg-+AG0-+AGw-+AD4-+ADw-+AFg-+AFg-+AEU-+AC8-+AD4-+ADw-+AC8-+AHg-+AG0-+AGw-+AD4-

**Comment by hackvertor** [comment]
Hiya, yep agreed I will add it in the next release.

**Comment by ngregoire** [comment]
Thanks, looking forward!
