### ISSUE TITLE
Scan not fully working with HackVector

### ISSUE THREAD

**Issue by Hipapheralkus** [hackvertor/hackvertor#12]
Hi,
I have hackvector properly configured with following Repeater syntax:
`{"session":"<@base64_0><@set_var_2><Session><MaintainSession019>19</MaintainSession019></Session><@/set_var_2><@/base64_0>","hash":"<@sha1_1><@get_var_2 /><@/sha1_1>"}`
The idea is, Burp Scan should scan the XML, which is then base-64 encoded and SHA1 is calculated of the XML. Unexpectedly, I most of the times see only HackVector syntax in the Logger++, and not the base-64 encoded values.
When I check Logger++, while scanning, sometimes it uses good payloads:
{"session":"PFNlc3Npb24+PE1haW50YWluU2Vzc2lvbjAxOT4xOTwvTWFpbnRhaW5TZXNzaW9uMDE5PjwvU2Vzc2lvbj4=","hash":"86230db330d1b60d44065ffb5dc5dee24ad6d4a4}

However, with most of the requests, it doesn't work, as in the Logger++ I can only see Hackvector syntax, and not base-64 encoded payload, which should include the attack itself:

attack payload being `2ebdah41sr`:
`{"session":"<@base64_0><@set_var_2><Session><MaintainSession019>19<\/MaintainSession019><\/Session><@\/set_var_2><@\/base64_0>2ebdah41sr","hash":"da39a3ee5e6b4b0d3255bfef95601890afd80709"}`

attack payload being `]]&gt;&gt;&lt;`:
`{"session":"<@base64_0><@set_var_2><Session><MaintainSession019>19<\/MaintainSession019><\/Session><@\/set_var_2><@\/base64_0]]&gt;&gt;&lt;>","hash":"da39a3ee5e6b4b0d3255bfef95601890afd80709"}`

attack payload being: `xmlns=\"http:\/\/a.b\/\" xmlns:xsi=\"http:\/\/www.w3.org\/2001\/XMLSchema-instance\" xsi:schemaLocation=\"http:\/\/a.b\/ http:\/\/s4xz8zmnh77xczusvxcy1oc5awgw4osogg36rv.burpcollaborator.net\/@base64_0.xsd\"`
`{"session":"<@base64_0 xmlns=\"http:\/\/a.b\/\" xmlns:xsi=\"http:\/\/www.w3.org\/2001\/XMLSchema-instance\" xsi:schemaLocation=\"http:\/\/a.b\/ http:\/\/s4xz8zmnh77xczusvxcy1oc5awgw4osogg36rv.burpcollaborator.net\/@base64_0.xsd\"><@set_var_2><Session><MaintainSession019>19<\/MaintainSession019><\/Session><@\/set_var_2><@\/base64_0>","hash":"da39a3ee5e6b4b0d3255bfef95601890afd80709"}`

It seems to me, that Scan scans Hackvector's native XML tags, instead of those inside, which needs to be scanned instead, so invalid request goes to Logger++, and Server.

**Comment by hackvertor** [comment]
Hi Hipapheralkus, I think Hackvertor is working it's just that the scanner is transforming the Hackvertor tags. What you need to do is install the Scan Manual insertion point BApp. Then select the area you want to scan within the parameter, this will then ensure that your Hackvertor tags stay intact and the scanner only manipulates that manual insertion point.

**Comment by Hipapheralkus** [comment]
Thank you, I think I can do the same with Intruder -> Scan defined insertion points.
Still -> would it be possible to somehow hook transparently into the Scan? For example, if I go to Session Handling Rules -> Invoke a Burp extension. Could HackVector be somehow hooked there, so that every time Scanner sees payload, it only see it without HackVector tags? Or using any other way.
Or could specific tags be blacklisted in Scan to be ignored? E.g. if I could go to Ignored Insertion Points add any parameter name regexp "@[a-z0-9_ ]+"? Although it will probably not be working, because it would ignore everything within that tag... Although I'm not sure how scan behaves if such regexp would be "skipped for server-side injection tests", but "use nested insertion points" would be allowed. Would it even be scanned or not at all...?
All in all -> is there some way of Feature Request to the awesome HackVector, so that it would be better integrated into automated Scan?

**Comment by hackvertor** [comment]
I might improve this in future but for now please use the workaround suggested. Cheers.
