### ISSUE TITLE
Custom Tags are broken in Burp Suite Professional version 2024.9.3

### ISSUE THREAD

**Issue by izdiwho** [hackvertor/hackvertor#129]
As mentioned in the title, custom tags just doesn't work in the new version of burp. I don't see any error messages in the extensions output either.

To reproduce:
1) Create custom tags
2) Uncomment the base64 template
3) Test tag
4) Enter

Expected: Popup of Base64 output 
Result: Nothing happens

Tested on MacOS 15.0, Burp Suite Professional version 2024.9.3 (Apple Silicon)

**Comment by hackvertor** [comment]
Thanks, yeah I think this is specific to JavaScript tags. Graal has stopped working on the newer JRE :( I need to find a solution to make this work again

**Comment by izdiwho** [comment]
Alright, I guess I'll convert my custom tags to one of the other languages for now!
