### ISSUE TITLE
AES support

### ISSUE THREAD

**Issue by Abb4d0n** [hackvertor/hackvertor#13]
Hello,

is it possible to add support for AES en-/decryption with different modes (CBC, CTR, GCM,...) and paddings?

Thanks :)

**Comment by hackvertor** [comment]
Hi Abb4d0n, yes I can do that. I'm a bit busy right now but I'll add it in the next release. Cheers.

**Comment by hackvertor** [comment]
Hi Abb4d0n

I've added AES encryption/decryption. It should be in the BApp store this week. Cheers.

**Comment by Abb4d0n** [comment]
Hi,
thank you for implementing the AES support.

It would be nice if you could improve the functionality by allowing
- the use of different key lengths (at least 128 + 256)
- to specify the IV (not random) 
- to specify key and IV as base64 encoded string

I need to specify these values so that the server can decrypt the encrypted values.

According to your code the key is taken from the first 16 bytes of sha1 hash of the specified password. So the specified key is not really the key.
Additionally, by using a random IV you won't be able to decrypt the previously encrypted data because you don't know the IV.

Thanks :)

**Comment by hackvertor** [comment]
Hi Abb4d0n 

Yeah sure I can improve it. I'll reopen this issue until the changes are done.

Cheers

**Comment by hackvertor** [comment]
Hiya, sorry for the delay but I've just pushed the changes discussed. It will be on the BApp store shortly. Cheers.
