### ISSUE TITLE
Hackvertor Replacement does not work in Proxy Message Editor Tab

### ISSUE THREAD

**Issue by soffensive** [hackvertor/hackvertor#14]
I am using Hackvertor v1.2 from the Burp App Store and noticed that Hackvertor tags edited directly in the Proxy message editor tab will not be processed.

For example, in the HTTP body the following payload will be sent directly to the server without processing by Hackvertor:

`param=<@urlencode_0><@base64_1>manipulated</@base64_1></@urlencode_0>`

Is this expected behaviour ? I recall vaguely that it used to work at some point.

**Comment by hackvertor** [comment]
Hi soffensive, by default Hackvertor does not allow tags in the proxy. You can enable them in the Hackvertor menu:
Hackvertor->Allow tags in proxy

Cheers
