### ISSUE TITLE
Unexpected variable behaviour

### ISSUE THREAD

**Issue by snooze6** [hackvertor/hackvertor#15]
I've recently started fidgeting with Hackvertor and it's been a really helpful tool so far so congrats for the good job, notwithstanding, there is a behavior that I don't fully comprehend. When using variables like for example:

```
<@set_var_0>0<@/set_var_0>
<@set_var_1>1<@/set_var_1>
<@set_var_2>2<@/set_var_2>

<@get_var_0 />
<@get_var_1 />
<@get_var_2 />
```

I thought it will respond with

```
0
1
2

0
1
2
```

However it is not the case, as the following image shows:

![variable stuff](https://user-images.githubusercontent.com/9949680/87402405-cdc4bb80-c5bb-11ea-9214-7e536528313c.png)

I'm using hackvertor v1.4.1 from BApp store as suggested by the installation procedure.

Although most of the features are clear, due to the lack of documentation I cannot distinguish if I am using variables in an unintended way.

**Comment by hackvertor** [comment]
Hi snooze6 

Ah yeah this is quite confusing. The problem is Hackvertor creates unique numbers for every tag you add so in fact you are only using one Hackvertor variable here called "var". These unique numbers will be removed when I find the time to write a tag parser. 

Cheers

**Comment by snooze6** [comment]
Hi hackvertor and thanks for the fastest response that I've ever had in GitHub.

So it was true, I was misusing the variable tags. The correct way to use it is giving each variable a different name:

```
<@set_var_0>0<@/set_var_0>
<@set_asd_1>1<@/set_asd_1>
<@set_dfg_2>2<@/set_dfg_2>

<@get_var_0 />
<@get_asd_1 />
<@get_dfg_2 />
```

Thanks again for your extension, I'll close the issue as it is solved.
