### ISSUE TITLE
Use Default Editor / Monospace Font

### ISSUE THREAD

**Issue by einfallstoll** [hackvertor/hackvertor#16]
I didn't notice Hackvertor does not use a Monospace font until today. I analyzed a hash made a guess it could be SHA-256 and tried to confirm this. I looked at them and threw my idea away, because the length didn't match:

![image](https://user-images.githubusercontent.com/619048/89008781-8d7b7200-d30b-11ea-95be-c6d91a2a021f.png)

After a while I came back to my idea and then it hit me: Hackvertor doesn't use a monospace font. I quickly checked the length of both hashes... 64 characters, but they *appear* to be different.

I would expect Hackvertor to either use a Monospace font (by default or with an option) or at least use the default editor of Burp (which at least in my case uses a Monospace font).

**Comment by hackvertor** [comment]
Hi einfallstoll 

Yes agreed I'll make it monospace when I get chance. It should be in the next release. When I add it I'll close this issue.

Cheers

**Comment by hackvertor** [comment]
I've made all JTextArea's use a monospace font. This will be on the BApp store soon.

**Comment by einfallstoll** [comment]
Awesome! Thank you!
