### ISSUE TITLE
Minor project suggestions

### ISSUE THREAD

**Issue by h3xstream** [hackvertor/hackvertor#2]
## GroupId

The [`groupId`](https://github.com/hackvertor/hackvertor/blob/master/pom.xml#L7) should be unique to the project. By convention, it is usually the organization domain plus the project name.

Suggestion:
`<groupId>uk.co.hackvertor</groupId>` or 
`<groupId>uk.co.hackvertor.hackvertor-burp</groupId>`

https://maven.apache.org/guides/mini/guide-naming-conventions.html
https://github.com/hackvertor/hackvertor/blob/master/pom.xml#L7

## .gitignore

The `.idea/` folder and the eclipse files `.classpath/` `.project/` do not need to be commited. It is likely to create conflict since the files describe the local settings. A .gitignore could be configured in that regard.
The `pom.xml` file is sufficient to open the project in both Eclipse and IntelliJ.

## Version

https://github.com/hackvertor/hackvertor/blob/master/pom.xml#L9
https://github.com/hackvertor/hackvertor/blob/master/src/main/java/burp/BurpExtender.java#L410

**Comment by hackvertor** [comment]
Thanks very much! I've implemented your recommendations
