### ISSUE TITLE
FR: File reader (binary/string)

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#20]
A tag to read a file from filesystem to extract its contents. It should support binary and string separately I think (encoding matters probably).

This can be useful for file upload issues + when a payload is being created in a file using another process (like when XXE is being embedded in a DOCX file)

**Comment by floyd-fuh** [comment]
I think this question was made obsolete by the Python tag, just enable code execution tags and use:
`<@python('output = file(input).read()','REPLACED')>/etc/hosts<@/python>`
Works perfectly fine here.

**Comment by hackvertor** [comment]
Yep agreed

**Comment by irsdl** [comment]
I think this needs to be reopened to be implemented in Java given jython has a massive performance issue in Burp Suite at the moment. Additionally, we can almost implement all tags in Python so not sure why this does not deserve its own tag.

**Comment by irsdl** [comment]
`file(input).read()` also has problem with binary files. I just tried to read a zip file using this approach and the file has been mangled. I am going to find the right code but this is a hassle that HV can prevent.

**Comment by irsdl** [comment]
This is for binary for-future-reference:
```
<@python('output = open(input, "rb").read()','TBR')>File Path<@/python>
```
