### ISSUE TITLE
FR: Web page reader (binary/string)

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#22]
A tag to read a file from a URL to extract its contents. It should support binary and string separately I think (encoding matters probably).

This can be useful when paylaods are being stored in an external website like in GitHub gists or raw pages.

**Comment by freeAhao** [comment]
I think you can create a custom tag to handle this.

Or use burpsuite's Macros and Session Handling Rules In Project options -> Sessions.

It would be great if we can call burp's macros in extension.
