### ISSUE TITLE
FR: Tag exporter / importer

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#23]
This is to share tags with other users as well as keeping a backup of what we have so we can put it in places like GitHub.

It can perhaps import from a file, directory, or a URL with some validation to make sure it is actually a custom tag. 

Perhaps some metadata need to be added to the top of each custom tag to show its type, usage, requirements, author, credit etc

**Comment by hackvertor** [comment]
You can already import/export tags to/from the clipboard. But yeah you're right there's no validation and it overwrites them all.  I need a nice way of sharing tags that isn't too painful to code review.

**Comment by hackvertor** [comment]
This has now been done. Export/load JSON and we now have a tag store too.
