### ISSUE TITLE
RegEx replace needs double escaping

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#26]
The following does not work:
```
<@regex_replace_2("\s","")>
```

This is how we can currently do this:
```
<@regex_replace_2("\\s","")>
```

It shows that \ needs to be escaped which was ok if it was in a JS code for example but HV should be able to handle this as this will add confusion.

**Comment by hackvertor** [comment]
I was trying to emulate the behaviour of JavaScript strings here. I'm a bit torn on this one. Since you can do stuff like \x61 within a parameter.

**Comment by irsdl** [comment]
As we are in RegEx context in the first variable, I think it will be confusing to have double escaping. RegEx does support \x61 on its own :)

**Comment by hackvertor** [comment]
This should be fixed in the next release.
