### ISSUE TITLE
FR: Group tags

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#28]
I thought this had been implemented but I could not find it. It would be great if we can create group tags and save multiple tags as one tag.

Perhaps group tags can also use custom tags but allowing group tags in group tags can cause issues I guess ;)

**Comment by hackvertor** [comment]
I've thought about this but there are a few problems. 

-What if the tag doesn't exist anymore?
-What if the group tag contains a dangerous tag such as JavaScript, how do we ensure you can't pwn the user?
-What if a tag is renamed?

If all these can be resolved then I'll definitely do it.

**Comment by irsdl** [comment]
I think it should just stop processing if any of these errors occurred (if tag does not exist or has been renamed), add a note to the output or error panel in the extender tab, and send the request as is. We can always use invalid tags anyway in the request and HV ignores them and treats them as string at the moment.

if a user has not enabled code exec then they should not work and should be treated as string or completely ignored - as we are making group tags based on existing tags with their input parameters, exec tags should also have their tokens anyway but group tags themselves can be protected using a token as well, right?

**Comment by hackvertor** [comment]
If you create a tag group with a code execution tag such as JavaScript, an attacker could use this group to attack you without needing to know the code execution key. Also the tag group would stop working when Hackvertor is reloaded and the code execution key changes.

**Comment by hackvertor** [comment]
Sorry yes I've re-read your comment. Yep we could assign a token for the group, I guess when you create the group I could add a placeholder for the token.

**Comment by hackvertor** [comment]
You can now define tags inside custom tags therefore group tags aren't needed since you can just generate them however you like.

E.g.
output = convert("<@base64>"+input+"<@/base64>")
