### ISSUE TITLE
Custom tags not refreshed

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#29]
Custom tags in the right click menu are not updated when adding a new custom tag. The Custom tab in HV still needs a refresh too by switching to another tab first.

![image](https://user-images.githubusercontent.com/1798313/95664926-aa21fa80-0b43-11eb-8368-3369c38b558a.png)

I am using v1.5.3

**Comment by irsdl** [comment]
I can only fix this issue by reloading the extension at the moment.

**Comment by hackvertor** [comment]
Oh really? I thought I fixed this in 1.53. I'll double check

**Comment by hackvertor** [comment]
They don't refresh until you click the custom tags tab but it does refresh the right click menu as far as I can tell. Please can you give me some repo steps?

**Comment by irsdl** [comment]
It does not do it for me. Here is what I do:
1- I click on HV from the top menu
2- I select create custom tag
3- I call it foobar and click create
4- I go to the repeater tab, I right click in a request and choose HV but foobar is not listed in the custom tag

I am using burp suite installer in Windows if that matters (with the latest version of Burp Suite Pro).

**Comment by hackvertor** [comment]
Should be fixed in the next release!
