### ISSUE TITLE
Long search results without horizontal scroll

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#33]
The following photo should shows it all:
![image](https://user-images.githubusercontent.com/1798313/102238343-8a190980-3eed-11eb-85fb-6d30b14ebdfe.png)

it needs a horizontal scroll or something like that.

**Comment by hackvertor** [comment]
Ah good spot. Thanks. I'll fix it when I have time

**Comment by hackvertor** [comment]
Fixed. This will be in the next release.
