### ISSUE TITLE
Variables are UNDEFINED if used before being set

### ISSUE THREAD

**Issue by 1lastBr3ath** [hackvertor/hackvertor#39]
Previously, we could use variables anywhere we like. Now, it seems like we must first define the variable before using it, else it returns `UNDEFINED`. 
![Screen Capture_select-area_20210125095655](https://user-images.githubusercontent.com/7494618/105686758-b88ff880-5f1f-11eb-82db-81cc75687a9c.png)

**Comment by hackvertor** [comment]
Thanks to freeAhao this has been fixed in v1.6.2
