### ISSUE TITLE
FR: SAML Request DEFLATE

### ISSUE THREAD

**Issue by Selora** [hackvertor/hackvertor#49]
Hi there,
SAML requests are using a URL-encoded, base64'd deflated XML blob.
The deflate algorithm apparently is fixed by the standard so the headers are not present in the request, reducing its size.

Please add a deflate_SAML so SAML requests can be decoded by Hackvertor!

**Comment by hackvertor** [comment]
This has now been done and will be in the next release. I've created two new tags:
<@saml><@/saml>
<@d_saml><@/d_saml>

The first will encode a SAML request by compressing it with DEFLATE then base64 encoding it and then URL encoding it.
The second will decode the SAML request. I've also update the compression deflate tags to allow you to specify a header or not. Thanks for the request! Sorry it took so long.
