### ISSUE TITLE
urlencode_all does not properly encode single hex-digit bytes such as "\n"

### ISSUE THREAD

**Issue by cfreal** [hackvertor/hackvertor#5]
Hello ! The bug is pretty straightforward:
```
<@urlencode_all_1>
<@/urlencode_all_1>
```
should become:
```%0a```
but becomes:
```%a```

It breaks some parsers.
Culprit: https://github.com/hackvertor/hackvertor/blob/master/src/main/java/burp/BurpExtender.java#L1545
Suggestion: `converted.append("%" + String.format("%02X", codePoint));`

Thank you for this amazing tool :)

**Comment by hackvertor** [comment]
Great spot! Thanks. I've pushed the changes but it won't be in the BApp store yet.
