### ISSUE TITLE
Token incrementator

### ISSUE THREAD

**Issue by Hipapheralkus** [hackvertor/hackvertor#51]
Could you please add some token incrementation? If in my requests, there is a numerical token like 1234, and in the next request it needs to be incremented to 1235, so that the Hackvector would remember this token as well. E.g. when I Scan a request containing Hackvector syntax, it would still be incrementing the token based on the "internally saved" value.

**Comment by hackvertor** [comment]
Ah yeah this is a good FR. I'll create a global variable tag that will reimplement this functionality cheers

**Comment by hackvertor** [comment]
I've implemented this FR. Now you can make variables global like this:

<@set_variable1('true')>test<@/set_variable1>

And then in any other Hackvertor interface you can use them
