### ISSUE TITLE
Javascript custom tag not working

### ISSUE THREAD

**Issue by Hipapheralkus** [hackvertor/hackvertor#52]
When I try to write a custom tag in Javascript, even the pre-defined template one:
![image](https://user-images.githubusercontent.com/4717664/120994603-ee25d780-c784-11eb-8cfe-8b5836312684.png)
when I enable custom tag execution and try to test it, I get empty output:
![image](https://user-images.githubusercontent.com/4717664/120994676-00077a80-c785-11eb-823e-8757aa4373e1.png)
There is no error or output in Extender tabs, but it seems javascript is not working for custom tags.

**Comment by hackvertor** [comment]
Hiya, yeah I'm aware of this issue. It's because Nashorn has been deprecated in Java 15. I'm planning to use an alternative but for now the workaround is to use JRE <= 14 cheers

**Comment by hackvertor** [comment]
This will be fixed in the next release whoo hoo :)
