### ISSUE TITLE
Parsing error with HTTP/2 and tags containing space characters

### ISSUE THREAD

**Issue by ngregoire** [hackvertor/hackvertor#55]
# Context

Burp Suite Pro 2021.8.4 + Hackvertor 1.7.0
Repeater, HTTP/2, GET request

# Description

Parameter values with Hackvertor tags containing space characters break syntax parsing
The right part of the tag is removed

# How to reproduce

In Repeater, send a HTTP/1 request like the following (note the space character inside the `urlencode` tag)

    GET /?id=<@urlencode>abc def<@/urlencode> HTTP/1.1
    Host: somewhere

Using Inspector, change the protocol to HTTP/2. The result is the following incorrect request

    GET /?id=<@urlencode>abc HTTP/2
    Host: somewhere
 
Same outcome if we start from a HTTP/2 request, add a Hackvertor tag containing spaces and press Send

**Comment by hackvertor** [comment]
This is a Burp bug not really much I can do about this

**Comment by hackvertor** [comment]
Spoken with James about this and it isn't a Burp bug it's because H2 requests won't be well formed.  James said I can patch this in Hackvertor by using the Montoya API to manipulate the requests. I'll reopen this issue.

**Comment by ngregoire** [comment]
This issue appears to be solved (tested today on a HTTP/2 request with Burp Suite Pro 2023.10.3.4-24713 and Hackvertor v1.7.49). However, newlines inside Hackvertor tags are still unsupported (cf issue https://github.com/hackvertor/hackvertor/issues/80)
