### ISSUE TITLE
HackVertor changes mouse hover behaviour on Burp tool menu

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#56]
After adding the extension, Burp tools menu behaves differently and hovering the mouse does not select them. 

Here is the screenshot of normal behaviour when mouse is over the "User options":
![image](https://user-images.githubusercontent.com/1798313/136821521-c99a800f-7a4c-40fc-a449-e052d8cd177e.png)

Here is the result after adding HV 1.7 and hovering the "User options":
![image](https://user-images.githubusercontent.com/1798313/136821717-c5fc4897-10ad-4407-a316-7d75297f4c72.png)

It flickers sometimes and come to life so I think something is messing with the menu.

In addition to the latest version, I tried this using HV 1.5 and the result is the same.

**Comment by hackvertor** [comment]
This seems fixed now. I didn't do anything :)
