### ISSUE TITLE
Request: Make hackvertor context aware

### ISSUE THREAD

**Issue by jstnkndy** [hackvertor/hackvertor#58]
First of all, thanks for all of your hard work on this project, it's an invaluable tool!

The request I have is to make hackvertor context aware of the request it's being sent in. This would include the ability to access request's attributes such as the request path, header key/value pairs, etc... I could see this being immediately useful in a situation where an HMAC is generated based on the request being made.

Cheers!
Justin

**Comment by hackvertor** [comment]
Thanks Justin, so would you want some tags that return headers depending on what context you are in? I could also pass them to custom tags to if that would be helpful.

**Comment by jstnkndy** [comment]
Yep, exactly.

**Comment by hackvertor** [comment]
I think I've done this. You can use context tags to get the header value you want or URL information:

<@context_url("$protocol $host $path $file $query $port")/>
<@context_header("$headerName")/>

Hope I've understood the requirements cheers
