### ISSUE TITLE
Convert functions without delimiters

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#59]
the input parameter in `dec2hex` for example cannot be removed as it starts decoding every digits separately essentially getting numbers from 0 to 9 to decode.

Example:

```
<@dec2hex('')>65<@/dec2hex>
```

Result:

```
06,05
```

I think a better behaviour would be to do a smart decode by going through all the numerical group counts , something like this would do I guess:

```
(\d+)
```

**Comment by hackvertor** [comment]
This has been resolved in the next release
