### ISSUE TITLE
Enable use of HackVertor in requests made by extensions.

### ISSUE THREAD

**Issue by CoreyD97** [hackvertor/hackvertor#6]
Currently, only requests made by proxy, intruder, repeater and scanner can make use of Hackvertor.

It would be useful to allow requests made by extensions to also be processed by hackvertor, combining the functionality of both extensions.

**Comment by hackvertor** [comment]
Great suggestion! This would be very useful. How would you propose the API would work?

**Comment by CoreyD97** [comment]
No need for an API I don't think :)

Adding EXTENSION to the switch statement at the top of processHttpMessage and an appropriate options switch, the extension may detect requests on the way out and carry out its checks for Hackvertor tokens before making the appropriate replacements.

**Comment by hackvertor** [comment]
Even better :)

Done. It's in github now. Should be in the BApp store soon.
