### ISSUE TITLE
FR: Adding faker data

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#61]
It would be great to have a faker library similar to https://learning.postman.com/docs/writing-scripts/script-references/variables-list/ to generate fake data for different things.

**Comment by hackvertor** [comment]
Cool yeah I can see how that would be useful. I've not had a lot of time to work on Hackvertor but I'll try and sort some of these issues eventually.

**Comment by hackvertor** [comment]
This has been done! Thanks for the great suggestion!

Here's how it works, there are a number of fake tags:
Input: <@fake_address("$streetAddressNumber, $streetAddress, $secondaryAddress, $streetPrefix, $streetSuffix, $fullAddress, $buildingNumber, $countryCode, $timeZone, $streetName, $zipCode, $stateAbbr, $citySuffix, $cityPrefix, $city, $cityName, $firstName, $latitude, $longitude, $lastName, $state, $country","en-GB")/>

Output:
675, 724 Hegmann Throughway, Suite 799, xx, Estates, Apt. 878 60404 Mante Rapid, South Bruce, LA S04 2XN, 139, GB, Europe/Vienna, Bartoletti Brook, W98 6AB, AL, chester, East, Leoside, LeosideName, Felix, -16.702014, 70.309537, Kemmer, Montana, Montenegro
