### ISSUE TITLE
FR: random tag option to use full input charset

### ISSUE THREAD

**Issue by floyd-fuh** [hackvertor/hackvertor#62]
Would it be possible to have an additional argument to the random tag, which would define if all characters from the input has to be used? That would simplify being compliant with a password policy. Here's what I mean:

`<@random(10)>ABC<@/random>`

Would currently generate:
`ABBBBCAABC`
But could also generate:
`AAABBAAABB`

I would like a parameter (true/false) that tells it to at least use every character once, meaning:

`<@random(10, true)>ABC<@/random>`

Could still generate the first example above, but would never generate the second example, because C is not in the output. This would help if we have to set a random password:

`<@random(15, true)>aceFHJ135.-,@!<@/random>`

Would then for sure create a password that is strong enough for most password policies.

A nice side effect is that it is also possible to create permutations of a word with that:

`<@random(4, true)>ABCD<@/random>`

Could create:

ABCD
BACD
BCAD
BCDA
ACBD
ACDB
ABDC
CABD
CADB
CBAD
CBDA
CDAB
CDBA
etc.

But it's a lot more predictable if the character set is important to the server.

**Comment by hackvertor** [comment]
Ah great suggestion. Yeah I'll do that, can't promise when though as I'm busy at work and do this in my spare time. If you need this functionality urgently then a custom tag could do the job cheers

**Comment by floyd-fuh** [comment]
Is it possible to create a custom tag or a code execution tag from another extension?

**Comment by hackvertor** [comment]
This should be in the next release
