### ISSUE TITLE
Make hackvertor use the user specified font? 

### ISSUE THREAD

**Issue by scarletturtle** [hackvertor/hackvertor#66]
Would be really great if hackvertor could use the user set fonts and sizes the way repeater and other tabs use.

**Comment by ngregoire** [comment]
+1!

I increase the editor's font size when giving trainings but that doesn't impact Hackvertor tabs. Too bad...

Note that vision-impaired people are impacted too and can barely use the tool.

**Comment by hackvertor** [comment]
Agreed I'll do this at some point

**Comment by hackvertor** [comment]
This has been fixed and will be in the next release. Changing the font size and reloading the extension will now use Burp's font size settings whilst retaining a fixed width font.
