### ISSUE TITLE
Can variables be used in tags' parameters?

### ISSUE THREAD

**Issue by ngregoire** [hackvertor/hackvertor#67]
Hi! I have a situation where requests' headers include a HMAC of the body, signed with a piece of data also transmitted via headers. I thought the problem could be solved using variables, but that doesn't work as expected.

Here's what I tried:
```
[...]
X-Csrf-Token: <@set_token('true')>jhcgdjhcg126dcdckhkj<@/set_token>
X-Signature: <@hmac_sha1("<@get_token/>")><@get_body/><@/hmac_sha1> 
[...]

<@set_body('true')>name=joe&surname=john&role=admin<@/set_body>
```

But `hmac_sha1()` uses the string `<@get_token/>` as the secret, instead of the string stored in the variable `token` (here `jhcgdjhcg126dcdckhkj`). Hence, the HMAC is invalid.

Is that expected? Any know way to get the behavior I'm looking for?
Thanks in advance!

**Comment by hackvertor** [comment]
Ah the old Hackvertor used to allow this but the new tag parser will not allow tags inside tag params. I'll think the best way to solve this, the old method is more powerful but could be buggy.

**Comment by ngregoire** [comment]
So I'm crazy, it worked at some point. Good to know!

**Comment by ngregoire** [comment]
I found a workaround, by using a custom tag and removing params entirely:
```
import hashlib
import hmac
import base64

key, message = str(input).split('===')

digester = hmac.new(key, message, hashlib.sha1)
sig = digester.hexdigest()

output = sig
```

To be used like that:
`<@_hmac_sha1('code_exec_key')><@get_token/>===<@get_body/><@/_hmac_sha1>`

**Comment by hackvertor** [comment]
All tags are now allowed in attributes/parameters. Should be in the next release.
