### ISSUE TITLE
FR: e_js_string

### ISSUE THREAD

**Issue by h1pmnh** [hackvertor/hackvertor#70]
Maybe I can't find it but I don't see the Encode counterpart of the `d_js_string` tag, which would be very helpful when dealing with JSON objects. Would it be possible to either add this or point me at which built-in tag does this?

Many thanks!

**Comment by hackvertor** [comment]
There's no tag at the moment that does this but I plan to add all sorts of JSON tags in future. In the meantime you can use custom tags to replicate this.

**Comment by hackvertor** [comment]
This has now been added and will be available in the next release.
