### ISSUE TITLE
FR: Updating the custom tag editor

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#72]
It would be great if the custom tag editor can be replaced with a better editor such as https://github.com/bobbylight/RSyntaxTextArea

**Comment by irsdl** [comment]
Here is how it looks like: http://bobbylight.github.io/RSyntaxTextArea/

**Comment by hackvertor** [comment]
This has been done now. The Hackvertor main interface has syntax highlight and code completion and the custom tags has it too.
