### ISSUE TITLE
Find using capture groups

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#77]
Currently the `find` tag uses regex but it has no concept of capture groups. It would be good to evolve the `find` tag so it can display the identified capture groups only. This can be very useful when extracting some data from json string for example.

**Comment by hackvertor** [comment]
I've enhanced the tag to allow groups:

find(String str, String find, int group)

Input: <@find('(a)b',1)>ab<@/find>
Output: a

Default is -1 for group
