### ISSUE TITLE
Support for JWT alg: none

### ISSUE THREAD

**Issue by einfallstoll** [hackvertor/hackvertor#8]
The implementation should support no signature / encryption algorithm as well

**Comment by hackvertor** [comment]
Thanks, yep I'll add that to the tag. Should be in the next few weeks when I get round to doing an update.

**Comment by einfallstoll** [comment]
Added in ce1adc1b79870ae4f233631bdd62257a6c690572

**Comment by hackvertor** [comment]
Thanks for closing I forgot. Cheers.
