### ISSUE TITLE
FR: Add tags "SPACE" and "NEWLINE"

### ISSUE THREAD

**Issue by ngregoire** [hackvertor/hackvertor#80]
Given that using space and newline characters inside Hackvertor tags break Burp syntax parsing, it could be useful to add two very simple tags, `space` and `newline` (or `sp` and `nl`). We could then use them instead of the raw characters, hence working around this limitation.

**Comment by hackvertor** [comment]
I'll try and fix the repeater problems with Montoya. If not I'll implement this.

**Comment by ngregoire** [comment]
The issue with space characters appears to be solved (tested today on a HTTP/2 request with Burp Suite Pro 2023.10.3.4-24713 and Hackvertor v1.7.49). Newlines inside Hackvertor tags are still unsupported.

**Comment by hackvertor** [comment]
Tested on 2023.11.1.3 and seems fixed!

**Comment by ngregoire** [comment]
Tested with Hackvertor 1.7.49 and v1.8.9 + Burp Suite Pro v2023.11.1.2

The issue with SPACE characters was fixed at the Burp level and that's fine (even if syntax highlighting still breaks as soon as we enter a space). However, we still have problems with newlines inside Hackvertor tags.

That's why I reiterate my requests for 2 simple tags: `<sp/>` and `<nl/>`

**Comment by ngregoire** [comment]
Hum... It seems I can't re-open the issue :-/

**Comment by hackvertor** [comment]
I've added those two helper tags. in v1.8.10

**Comment by ngregoire** [comment]
Awesome, thanks!
