### ISSUE TITLE
Could not load J2V8 library in Windows

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#84]
I am getting the following error in Windows when using custom tag with JS:

```
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library.
```

I can see the following lib in the gradle:
```
'com.eclipsesource.j2v8:j2v8_macosx_x86_64:4.6.0'
```
Is this just for Mac OS or do we need to install an extra package anyway?

**Comment by hackvertor** [comment]
I couldn't get it to work on other platforms, tried for ages in the end I gave up

**Comment by Pcoder7** [comment]
I found the same Error. Did you found a workaround how to make custom tag in Windows without throwing this error

**Comment by hackvertor** [comment]
Sorry JS can't currently work on Windows since it doesn't have the binaries. I can look at this once I've done the work for tag store. The workaround is to use any other language other than JS.

**Comment by hackvertor** [comment]
Fixed this. JavaScript should now work on all platforms!
