### ISSUE TITLE
@context_header stops at first colon

### ISSUE THREAD

**Issue by acut3** [hackvertor/hackvertor#88]
With the following header:

```http
X-Timestamp: Fri, 05 May 2023 10:41:36 GMT
```

hackvector expression `<@context_header("$X-Timestamp")/>` returns `Fri, 05 May 2023 10` instead of the expected `Fri, 05 May 2023 10:41:36 GMT`. Meaning, it stops at the first colon instead of capturing the whole value.

**Comment by hackvertor** [comment]
Good catch thanks :) this was because I forgot there could be more than one colon in the value and I didn't join the rest of the array. This is fixed in v1.7.45
