### ISSUE TITLE
FR: raw inflate addition

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#90]
It would be good to have a raw inflation for decompression or compression when it does not use any headers. Cyberchef also has it:
![image](https://github.com/hackvertor/hackvertor/assets/1798313/847381d5-18c7-48f9-9110-c58f5f3afabf)

I wonder if we can come up with an easy solution to import cyberchef in HV somehow.

**Comment by hackvertor** [comment]
Hackvertor has it too:
```XML
<@deflate_compress(false)>abc<@/deflate_compress>
```

The flag is used to determine to set the header or not.  Integrating CyberChef is an interesting idea, I'll look into it.

**Comment by irsdl** [comment]
I didn't know about the flag. I should have looked better.
