### ISSUE TITLE
FR: Tag for save to file

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#93]
It would be good to have a save to file tag. Here is how I have done it in a custom tag in python:

Here are the input variables:
![image](https://github.com/hackvertor/hackvertor/assets/1798313/a9cbc359-17e9-4613-816f-244df8850c87)

Here is the code:
```
def save_to_file(filename, text):
    """
    Save the given text to the specified file.

    Parameters:
    - filename (str): The name of the file where the text should be saved.
    - text (str): The text that needs to be saved.

    """
    with open(filename, 'w') as file:
        file.write(text)

# Example usage:
if enabled > 0:
	save_to_file(filePath, input)
output=""
```

**Comment by hackvertor** [comment]
Again this would be good for the tag store

**Comment by hackvertor** [comment]
Tag store will be in the next release. This is perfect for that!
