### ISSUE TITLE
FR: output void tag!

### ISSUE THREAD

**Issue by irsdl** [hackvertor/hackvertor#94]
Sometimes we do not want the result of a tag to be added to a request. It would be good to have a tag that can remove the output text of another tag like system.

Here is how I was doing this for a while in a custom tag:
![image](https://github.com/hackvertor/hackvertor/assets/1798313/bb5680c7-f90d-470b-8b1e-2f64050fca35)

**Comment by hackvertor** [comment]
Added a remove_output tag under string
