### ISSUE TITLE
Reusing a Hackvertor-generated value?

### ISSUE THREAD

**Issue by raynemaker0** [hackvertor/hackvertor#99]
Apologies if this is a silly question.

I'm testing an API which requires a unique UUID for the first part of the request, and the same one needs to be used towards the end. How would I achieve this? Obviously, using <@uuid/> twice will result in two different UUIDs - I need the same one. Is this doable?

**Comment by hackvertor** [comment]
Great question! Yes this is possible. You need to use tag variables:

```html
<@set_uid(false)><@uuid/><@/set_uid>
<@get_uid/>
````
The above creates a tag variable called uid and you can reuse the same random uid by placing <@get_uid/> anywhere in the request.
